name: Machine Learning CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        cache: 'pip' # <--- BLINDAJE 1: Cachea dependencias para ir 3x m치s r치pido

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-mock

    - name: Run Integrity and Unit Tests
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        pytest tests/test_models.py

    - name: Prepare Dummy Data for Docker
      run: |
        # Creamos las carpetas que Docker espera pero que no est치n en Git
        mkdir -p data/04_features models
        touch data/04_features/.keep models/.keep

    - name: Verify Docker Build
      run: |
        # BLINDAJE 2: Verifica que el "envase" (Docker) sea v치lido
        docker build -t risk-engine-test .
